name: checklist
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_text_kit: 4.2.1
  auto_route: 3.1.3
  bloc: 8.0.1
  bloc_test: 9.0.1
  cupertino_icons: 1.0.4
  easy_localization: 3.0.0
  equatable: 2.0.3
  fimber: 0.6.4
  firebase_auth: 3.2.0
  firebase_core: 1.10.0
  firebase_crashlytics: 2.3.0
  flutter:
    sdk: flutter
  flutter_bloc: 8.0.0
  fluttertoast: 8.0.8
  form_field_validator: 1.1.0
  get_it: 7.2.0
  hive: 2.0.4
  hive_flutter: 1.1.0
  local_auth: 1.1.8
  mocktail: 0.2.0
  provider: 6.0.1
  rive: 0.7.33

dev_dependencies:
  auto_route_generator: 3.1.0
  build_runner: 2.1.5
  flutter_test:
    sdk: flutter
  hive_generator: 1.1.1
  json_serializable: 6.0.1
  lint: 1.7.2

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/animations/
